name: multimodal
channels:
  - nvidia/label/cuda-11.4.0
  - anaconda
  - defaults
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - _anaconda_depends=2025.06
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aiobotocore=2.23.2
  - aiodns=3.5.0
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aioitertools=0.7.1
  - aiosignal=1.4.0
  - alabaster=0.7.16
  - altair=5.5.0
  - anaconda-anon-usage=0.7.2
  - anaconda-catalogs=0.2.0
  - anaconda-cli-base=0.5.2
  - anaconda-client=1.13.0
  - anaconda-cloud-auth=0.7.2
  - anaconda-navigator=2.6.4
  - anaconda-project=0.11.1
  - annotated-types=0.6.0
  - anyio=4.7.0
  - aom=3.6.0
  - appdirs=1.4.4
  - archspec=0.2.3
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - arrow=1.3.0
  - arrow-cpp=19.0.0
  - astroid=3.3.8
  - astropy=7.1.0
  - astropy-iers-data=0.2025.8.25.0.36.58
  - asttokens=2.0.5
  - async-lru=2.0.4
  - async-timeout=5.0.1
  - asyncssh=2.17.0
  - atomicwrites=1.4.0
  - attrs=24.3.0
  - automat=20.2.0
  - autopep8=2.0.4
  - aws-c-auth=0.9.0
  - aws-c-cal=0.9.2
  - aws-c-common=0.12.4
  - aws-c-compression=0.3.1
  - aws-c-event-stream=0.5.6
  - aws-c-http=0.10.4
  - aws-c-io=0.21.4
  - aws-c-mqtt=0.13.3
  - aws-c-s3=0.8.7
  - aws-c-sdkutils=0.2.4
  - aws-checksums=0.2.7
  - aws-crt-cpp=0.34.0
  - aws-sdk-cpp=1.11.638
  - babel=2.16.0
  - backcall=0.2.0
  - backports.tarfile=1.2.0
  - bcrypt=4.3.0
  - beautifulsoup4=4.13.5
  - binaryornot=0.4.4
  - black=25.1.0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.9.0
  - blosc=1.21.3
  - bokeh=3.7.3
  - boltons=25.0.0
  - boost-cpp=1.82.0
  - botocore=1.39.8
  - bottleneck=1.4.2
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brotlicffi=1.0.9.2
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.12.0
  - ca-certificates=2025.7.15
  - cachetools=5.5.1
  - cairo=1.16.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfitsio=3.470
  - chardet=5.2.0
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - click=8.2.1
  - cloudpickle=3.1.1
  - cmake=3.31.2
  - colorama=0.4.6
  - colorcet=3.1.0
  - comm=0.2.1
  - conda=24.11.3
  - conda-build=25.5.0
  - conda-content-trust=0.2.0
  - conda-index=0.6.1
  - conda-libmamba-solver=24.9.0
  - conda-pack=0.8.1
  - conda-package-handling=2.4.0
  - conda-package-streaming=0.12.0
  - conda-repo-cli=1.0.173
  - conda-token=0.5.0
  - constantly=23.10.4
  - contourpy=1.3.1
  - cookiecutter=2.6.0
  - cryptography=44.0.1
  - cssselect=1.2.0
  - cuda=11.4.0
  - cuda-cccl=11.4.43
  - cuda-command-line-tools=11.4.0
  - cuda-compiler=11.4.0
  - cuda-cudart=11.4.43
  - cuda-cudart-dev=11.4.43
  - cuda-cuobjdump=11.4.43
  - cuda-cupti=11.4.65
  - cuda-cuxxfilt=11.4.43
  - cuda-driver-dev=11.4.43
  - cuda-gdb=11.4.55
  - cuda-libraries=11.4.0
  - cuda-libraries-dev=11.4.0
  - cuda-memcheck=11.4.43
  - cuda-nsight=11.4.43
  - cuda-nsight-compute=11.4.0
  - cuda-nvcc=11.4.48
  - cuda-nvdisasm=11.4.43
  - cuda-nvml-dev=11.4.43
  - cuda-nvprof=11.4.43
  - cuda-nvprune=11.4.43
  - cuda-nvrtc=11.4.50
  - cuda-nvrtc-dev=11.4.50
  - cuda-nvtx=11.4.43
  - cuda-nvvp=11.4.43
  - cuda-runtime=11.4.0
  - cuda-sanitizer-api=11.4.54
  - cuda-toolkit=11.4.0
  - cuda-tools=11.4.0
  - cuda-visual-tools=11.4.0
  - curl=8.15.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=1.0.1
  - dask=2025.7.0
  - dask-core=2025.7.0
  - dask-expr=2.0.0
  - datashader=0.18.2
  - dav1d=1.2.1
  - dbus=1.13.18
  - debugpy=1.8.11
  - decorator=5.1.1
  - defusedxml=0.7.1
  - deprecated=1.2.13
  - diff-match-patch=20200713
  - dill=0.3.8
  - distributed=2025.7.0
  - distro=1.9.0
  - docstring-to-markdown=0.11
  - docutils=0.21.2
  - et_xmlfile=2.0.0
  - evalidate=2.0.3
  - exceptiongroup=1.2.0
  - executing=0.8.3
  - expat=2.7.1
  - ffmpeg=4.2.2
  - filelock=3.17.0
  - flake8=7.1.1
  - flask=3.1.2
  - fmt=9.1.0
  - fontconfig=2.14.1
  - fonttools=4.55.3
  - freetype=2.12.1
  - frozendict=2.4.2
  - frozenlist=1.5.0
  - gds-tools=1.0.0.82
  - gensim=4.3.3
  - gflags=2.2.2
  - giflib=5.2.1
  - git-lfs=3.6.1
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - gmp=6.2.1
  - gmpy2=2.1.2
  - gnutls=3.6.15
  - graphite2=1.3.14
  - greenlet=3.1.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.16.0
  - h5py=3.14.0
  - harfbuzz=4.3.0
  - hdf5=1.14.5
  - heapdict=1.0.1
  - holoviews=1.21.0
  - httpcore=1.0.9
  - httpx=0.28.1
  - hvplot=0.12.0
  - hyperlink=21.0.0
  - icu=73.1
  - idna=3.7
  - imagecodecs=2023.1.23
  - imageio=2.37.0
  - imagesize=1.4.1
  - imbalanced-learn=0.14.0
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.4.0
  - incremental=22.10.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=2.0.8
  - intel-openmp=2023.1.0
  - intervaltree=3.1.0
  - ipykernel=6.29.5
  - ipython=8.30.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.8.5
  - isort=6.0.1
  - itemadapter=0.3.0
  - itemloaders=1.3.2
  - itsdangerous=2.2.0
  - jaraco.classes=3.2.1
  - jaraco.context=6.0.0
  - jaraco.functools=4.1.0
  - jedi=0.19.2
  - jeepney=0.7.1
  - jellyfish=1.1.3
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.1
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.25.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.1.1
  - jupyter-lsp=2.2.5
  - jupyter_client=8.6.3
  - jupyter_console=6.6.3
  - jupyter_core=5.8.1
  - jupyter_events=0.12.0
  - jupyter_server=2.16.0
  - jupyter_server_terminals=0.5.3
  - jupyterlab=4.4.6
  - jupyterlab-variableinspector=3.2.4
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=1.0.0
  - jxrlib=1.1
  - keyring=25.6.0
  - kiwisolver=1.4.8
  - krb5=1.20.1
  - lame=3.100
  - lazy-object-proxy=1.10.0
  - lazy_loader=0.4
  - lcms2=2.12
  - ld_impl_linux-64=2.40
  - leptonica=1.82.0
  - lerc=3.0
  - libabseil=20250127.0
  - libaec=1.0.4
  - libarchive=3.6.2
  - libavif=0.11.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcublas=11.5.2.43
  - libcublas-dev=11.5.2.43
  - libcufft=10.5.0.43
  - libcufft-dev=10.5.0.43
  - libcufile=1.0.0.82
  - libcufile-dev=1.0.0.82
  - libcups=2.4.2
  - libcurand=10.2.5.43
  - libcurand-dev=10.2.5.43
  - libcurl=8.15.0
  - libcusolver=11.2.0.43
  - libcusolver-dev=11.2.0.43
  - libcusparse=11.6.0.43
  - libcusparse-dev=11.6.0.43
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.78.4
  - libgomp=11.2.0
  - libgrpc=1.71.0
  - libiconv=1.16
  - libidn2=2.3.4
  - liblief=0.12.3
  - libllvm14=14.0.6
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libnpp=11.4.0.33
  - libnpp-dev=11.4.0.33
  - libnvjpeg=11.5.1.43
  - libnvjpeg-dev=11.5.1.43
  - libogg=1.3.5
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=5.29.3
  - libre2-11=2024.07.02
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libspatialindex=1.9.3
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtasn1=4.19.0
  - libtheora=1.1.1
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.7.0
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.15
  - libxkbcommon=1.0.1
  - libxml2=2.10.4
  - libxslt=1.1.37
  - libzopfli=1.0.3
  - linkify-it-py=2.0.0
  - llvmlite=0.44.0
  - locket=1.0.0
  - lxml=5.2.1
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - markdown=3.8
  - markdown-it-py=2.2.0
  - markupsafe=3.0.2
  - matplotlib=3.10.0
  - matplotlib-base=3.10.0
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdit-py-plugins=0.5.0
  - mdurl=0.1.0
  - menuinst=2.3.1
  - mistune=3.1.2
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.11
  - mkl_random=1.2.8
  - more-itertools=10.3.0
  - mpc=1.1.0
  - mpfr=4.0.2
  - mpi=1.0
  - mpi4py=4.0.3
  - mpich=4.1.1
  - mpmath=1.3.0
  - msgpack-python=1.1.1
  - multidict=6.1.0
  - multipledispatch=0.6.0
  - mypy=1.17.1
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - narwhals=1.31.0
  - navigator-updater=0.5.1
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - nltk=3.9.1
  - notebook=7.4.4
  - notebook-shim=0.2.4
  - nsight-compute=2021.2.0.15
  - nspr=4.35
  - nss=3.89.1
  - numba=0.61.2
  - numexpr=2.11.0
  - numpydoc=1.9.0
  - oniguruma=6.9.7.1
  - openh264=2.1.1
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.0.17
  - orc=2.1.1
  - overrides=7.4.0
  - packaging=25.0
  - pandas=2.3.2
  - pandoc=2.12
  - pandocfilters=1.5.0
  - panel=1.7.5
  - param=2.2.1
  - parsel=1.8.1
  - parso=0.8.4
  - partd=1.4.2
  - patch=2.7.6
  - patchelf=0.17.2
  - pathspec=0.12.1
  - patsy=1.0.1
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=25.1
  - pixman=0.40.0
  - pkce=1.0.3
  - pkginfo=1.12.0
  - platformdirs=4.3.7
  - plotly=6.3.0
  - pluggy=1.5.0
  - ply=3.11
  - prometheus_client=0.21.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - propcache=0.3.1
  - protego=0.1.16
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-lief=0.12.3
  - pyarrow=19.0.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=4
  - pycares=4.10.0
  - pycodestyle=2.12.1
  - pycosat=0.6.6
  - pycparser=2.21
  - pyct=0.5.0
  - pycurl=7.45.6
  - pydantic=2.11.7
  - pydantic-core=2.33.2
  - pydantic-settings=2.6.1
  - pydeck=0.9.1
  - pydispatcher=2.0.7
  - pydocstyle=6.3.0
  - pyerfa=2.0.1.5
  - pyflakes=3.2.0
  - pygithub=2.4.0
  - pygments=2.19.1
  - pyjwt=2.10.1
  - pylint=3.3.5
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pynacl=1.5.0
  - pyodbc=5.2.0
  - pyopenssl=25.0.0
  - pyparsing=3.2.0
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - pytables=3.10.2
  - pytest=8.4.1
  - python=3.11.13
  - python-dateutil=2.9.0post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.20.0
  - python-json-logger=3.2.1
  - python-libarchive-c=5.1
  - python-lmdb=1.6.2
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.12.2
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - pytoolconfig=1.2.6
  - pytz=2025.2
  - pyuca=1.2
  - pyviz_comms=3.0.2
  - pywavelets=1.8.0
  - pyxdg=0.27
  - pyyaml=6.0.2
  - pyzmq=26.2.0
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.4.0
  - qtconsole=5.6.1
  - qtpy=2.4.1
  - queuelib=1.6.2
  - re2=2024.07.02
  - readchar=4.0.5
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.11.6
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.4
  - requests-file=1.5.1
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rhash=1.4.3
  - rich=13.9.4
  - rope=1.13.0
  - rpds-py=0.22.3
  - rtree=1.4.1
  - ruamel.yaml=0.18.10
  - ruamel.yaml.clib=0.2.12
  - ruamel_yaml=0.17.21
  - s2n=1.5.14
  - s3fs=2025.7.0
  - scikit-image=0.25.2
  - scikit-learn=1.7.1
  - scrapy=2.12.0
  - seaborn=0.13.2
  - secretstorage=3.3.1
  - semver=3.0.2
  - send2trash=1.8.2
  - service_identity=18.1.0
  - setuptools=78.1.1
  - shellingham=1.5.0
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=2.0.0
  - spyder=6.0.7
  - spyder-kernels=3.0.5
  - sqlalchemy=2.0.41
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.5
  - streamlit=1.48.0
  - superqt=0.7.3
  - tabulate=0.9.0
  - tbb=2021.8.0
  - tblib=1.7.0
  - tenacity=9.0.0
  - terminado=0.17.1
  - tesseract=5.2.0
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tinycss2=1.4.0
  - tk=8.6.14
  - tldextract=5.1.2
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.2
  - toolz=1.0.0
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - truststore=0.10.1
  - twisted=23.10.0
  - typer=0.9.0
  - typing-extensions=4.15.0
  - typing-inspection=0.4.0
  - typing_extensions=4.15.0
  - tzdata=2024b
  - uc-micro-py=1.0.1
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - unixodbc=2.3.11
  - urllib3=2.5.0
  - utf8proc=2.6.1
  - uvloop=0.21.0
  - w3lib=1.21.0
  - watchdog=4.0.2
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - werkzeug=3.1.3
  - whatthepatch=1.0.2
  - wheel=0.45.1
  - widgetsnbextension=3.6.10
  - wrapt=1.17.0
  - wurlitzer=3.0.2
  - x264=1!157.20191217
  - xarray=2025.4.0
  - xyzservices=2022.9.0
  - xz=5.6.4
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yapf=0.40.2
  - yarl=1.18.0
  - zeromq=4.3.5
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.21.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=7.1.1
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - absl-py==2.3.1
      - albucore==0.0.24
      - albumentations==1.0.3
      - audiomentations==0.42.0
      - audioread==3.0.1
      - av==14.0.1
      - beartype==0.21.0
      - coloredlogs==15.0.1
      - cython==3.1.3
      - datasets==3.5.1
      - decord==0.6.0
      - dlib==20.0.0
      - easydict==1.13
      - efficientnet-pytorch==0.7.1
      - einops==0.8.1
      - flatbuffers==25.2.10
      - fsspec==2025.3.0
      - grpcio==1.74.0
      - hf-xet==1.1.9
      - huggingface-hub==0.34.4
      - humanfriendly==10.0
      - imutils==0.5.4
      - insightface==0.7.3
      - jax==0.7.1
      - jaxlib==0.7.1
      - kornia==0.7.4
      - kornia-rs==0.1.9
      - librosa==0.10.2.post1
      - loralib==0.1.2
      - lpips==0.1.4
      - mediapipe==0.10.18
      - ml-dtypes==0.5.3
      - monai==1.5.0
      - multiprocess==0.70.16
      - networkx==3.5
      - numpy==1.26.0
      - numpy-minmax==0.5.0
      - numpy-rms==0.6.0
      - nvidia-cublas-cu11==11.11.3.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu11==9.1.0.70
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu11==2.21.5
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu11==11.8.86
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.19.0
      - onnxruntime==1.17.0
      - onnxruntime-gpu==1.22.0
      - opencv-contrib-python==4.11.0.86
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.12.0.88
      - opt-einsum==3.4.0
      - pillow==11.3.0
      - pooch==1.8.2
      - prettytable==3.16.0
      - protobuf==4.25.8
      - python-stretch==0.3.1
      - safetensors==0.6.2
      - scipy==1.16.1
      - sentencepiece==0.2.1
      - simsimd==6.5.3
      - sounddevice==0.5.2
      - soundfile==0.12.1
      - soxr==0.5.0.post1
      - stringzilla==3.12.6
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tifffile==2025.8.28
      - timm==1.0.19
      - tokenizers==0.21.4
      - torch==2.6.0+cu118
      - torchaudio==2.6.0+cu118
      - torchvision==0.21.0+cu118
      - transformers==4.49.0
      - triton==3.2.0
      - vidaug==1.5
      - xxhash==3.5.0
